framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
            - vendor/symfony/ux-live-component/assets
            - vendor/symfony/ux-autocomplete/assets
